[package]
name = "tydi-parser"
version = "0.1.0"
description = "Parser for tydi-lang"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"